//
// Created by os on 12/24/22.
//

#ifndef KERNEL_FOR_RISCV_ARCHITECURE_CONSTANTS_HPP
#define KERNEL_FOR_RISCV_ARCHITECURE_CONSTANTS_HPP

#include "../lib/hw.h"

#define BUDDY_BLOCK_BITS 12
#define BUDDY_BLOCK_SIZE 4096
#define BUDDY_NUMBER_OF_BLOCKS 4096
#define BUDDY_META_ADDR_CONST (void*)((((uint64)HEAP_START_ADDR >> BUDDY_BLOCK_BITS) + 1) << BUDDY_BLOCK_BITS)
#define BUDDY_START_ADDR_CONST (void*)((((uint64)HEAP_START_ADDR >> BUDDY_BLOCK_BITS) + 2) << BUDDY_BLOCK_BITS)
#define BUDDY_MEMORY_RESERVED HEAP_START_ADDR +
#define FREE_MEMORY_START_CONST (void*)((uint64)BUDDY_START_ADDR_CONST + (BUDDY_NUMBER_OF_BLOCKS << BUDDY_BLOCK_BITS))
#define BUCKET_SIZE 13

#endif //KERNEL_FOR_RISCV_ARCHITECURE_CONSTANTS_HPP
